apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: gameserver
spec:
  replicas: 2
  template:
    metadata:
      name: gameserver
      generateName: gameserver-
    spec:
      container: gameserver
      ports:
      - name: default
        containerPort: 10000
        protocol: TCP
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: gameserver
            image: gameserver:latest
            imagePullPolicy: Never
            resources:
              limits:
                memory: 16Mi
                cpu: 20m
            env:
            - name: RUST_LOG
              value: gameserver=debug
