apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: Never # for local
        ports:
        - name: grpc
          containerPort: 10001
        env:
        - name: RUST_LOG
          value: frontend=debug
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - name: grpc
    protocol: TCP
    port: 10001
