name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Submodule
      shell: bash
      run: git submodule update --init
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
